//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JinPlayer.rc
//
#define IDC_MYICON                      2
#define IDCANCEL2                       3
#define IDD_JINPLAYER_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_JINPLAYER                   107
#define IDI_SMALL                       108
#define IDC_JINPLAYER                   109
#define IDD_DIALOG_URL                  120
#define IDD_DIALOG_FILEINFO             121
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_EXIT                 130
#define IDR_MENU_POPUP                  131
#define IDD_DIALOG_UPDATE               131
#define IDD_DIALOG_NEWBOX               132
#define IDC_JINPLAYER_CHN               132
#define IDB_BITMAP_LOGO                 133
#define IDD_DIALOG_COPY                 133
#define IDR_MENU_POPUP1                 133
#define IDR_MENU_POPUP_CHN              133
#define IDD_DIALOG_IMPORT               134
#define IDD_DIALOG_OPENBOX              135
#define IDB_BITMAP_HOME                 147
#define IDB_BITMAP_VIDEO                150
#define IDB_BITMAP_VIDEO_NEW            151
#define IDB_BITMAP_IMAGE                152
#define IDB_BITMAP_AUDIO                153
#define IDB_BITMAP_FOLDER               154
#define IDB_BITMAP_FOLDER_NEW           155
#define IDC_BUTTON_OPEN                 1000
#define IDC_LIST_FILE                   1000
#define IDC_CHECK_VIDEODEC              1001
#define IDC_EDIT_URL                    1001
#define IDC_CHECK_DELETE                1001
#define IDC_EDIT_PW1                    1002
#define ID_BUTTON_ADD                   1002
#define IDC_EDIT_PW2                    1003
#define IDC_LIST_URL                    1003
#define ID_BUTTON_START2                1003
#define ID_BUTTON_START                 1003
#define IDC_EDIT_PATH                   1004
#define IDC_BUTTON_DELETE               1004
#define ID_BUTTON_DELETE                1004
#define IDC_BUTTON_FOLDER               1005
#define IDC_BUTTON_ADD                  1005
#define IDC_CHECK_CLOSE                 1005
#define IDC_STATIC_PW2                  1006
#define IDC_PROGRESS_COPY               1007
#define IDC_STATIC_PW                   1008
#define IDC_STATIC_PWINFO               1009
#define IDC_EDIT_ABOUT                  1010
#define IDC_BUTTON_START                1011
#define IDC_BUTTON_CANCEL               1012
#define IDC_EDIT_CHANGED                1013
#define IDC_PROGRESS_UPDATE             1015
#define IDC_STATIC_VER                  1016
#define IDC_BUTTON_0                    1016
#define IDC_BUTTON_1                    1017
#define IDC_BUTTON_2                    1018
#define IDC_BUTTON_3                    1019
#define IDC_BUTTON_4                    1020
#define IDC_BUTTON_5                    1021
#define IDC_BUTTON_6                    1022
#define IDC_BUTTON_7                    1023
#define IDC_BUTTON_8                    1024
#define IDC_BUTTON_9                    1025
#define IDC_BUTTON_STAR                 1026
#define IDC_BUTTON_CHA                  1027
#define IDC_BUTTON_DEL                  1027
#define ID_FILE_OPENFILE                32671
#define ID_FILE_OPENURL                 32672
#define ID_FILE_FOLDERVIEW              32673
#define ID_FILE_PLAYLISTVIEW            32674
#define ID_FILE_MYBOXVIEW               32675
#define ID_FILE_PROPERTIES              32676
#define ID_PLAY_AUDIO                   32677
#define ID_PLAY_SUBTITLE                32678
#define ID_PLAY_VIDEO                   32679
#define ID_SUBTITLE_ENABLE              32682
#define ID_SUBTITLE_DISABLE             32683
#define ID_SUBTITLE_F                   32684
#define ID_PLAY_NEXTFILE                32685
#define ID_PLAY_PREVFILE                32686
#define IDC_EDIT_FILE                   32687
#define ID_ZOOM_1                       32688
#define IDC_COMBO_FILE                  32689
#define ID_ITEM_PLAY                    32690
#define ID_VIDEO_DDRAW                  32691
#define IDC_PROGRESS_READ               32691
#define ID_ITEM_DELETE                  32692
#define ID_LANG_ENGLISH                 32693
#define IDC_BUTTON_READ                 32694
#define ID_MYBOX_NEWBOX                 32695
#define ID_LANG_CHINESE                 32696
#define IDC_EDIT_INFO                   32697
#define ID_MYBOX_OPENBOX                32698
#define ID_PLAY_PREV                    32699
#define ID_PLAY_PROPERTIES              32770
#define ID_PLAY_RETURN                  32771
#define ID_BOXITEM_EXPORT               32772
#define ID_PLAY_NEXT                    32773
#define ID_PLAY_ZOOM                    32774
#define ID_SUBTITLE_FONT                32775
#define ID_VIDEO_GDI                    32776
#define ID_VIDEOZOOM_1                  32801
#define ID_VIDEOZOOM_2                  32802
#define ID_VIDEOZOOM_3                  32803
#define ID_VIDEOZOOM_4                  32804
#define ID_VIDEOZOOM_5                  32805
#define ID_VIDEOZOOM_6                  32806
#define ID_VIDEOZOOM_7                  32807
#define ID_VIDEOZOOM_8                  32808
#define ID_VIDEOZOOM_9                  32809
#define ID_ZOOM_SELECT                  32810
#define ID_ROTATE_0                     32820
#define ID_ROTATE_90                    32821
#define ID_ROTATE_180                   32822
#define ID_ROTATE_270                   32823
#define ID_VIDEO_CAPTURE                32835
#define ID_PLAY_NEXT32816               32836
#define ID_PLAY_32817                   32837
#define ID_PLAY_CAPTURE                 32838
#define ID_PLAY_VIDEO32819              32839
#define ID_VIDEO_FULLSCREEN             32840
#define ID_PLAY_32821                   32841
#define ID_32822                        32842
#define ID_PLAY_SPEED                   32843
#define ID_PLAY_RATIO                   32844
#define ID_SPEED_0                      32855
#define ID_SPEED_1                      32856
#define ID_SPEED_2                      32857
#define ID_SPEED_3                      32858
#define ID_SPEED_4                      32859
#define ID_SPEED_5                      32860
#define ID_SPEED_6                      32861
#define ID_SPEED_7                      32862
#define ID_SPEED_8                      32863
#define ID_RATIO_ORIGINAL               32874
#define ID_RATIO_43                     32875
#define ID_RATIO_169                    32876
#define ID_RATIO_FITWINDOW              32877
#define ID_AUDIO_TRACK1                 33100
#define ID_HELP_UPDATE                  33204
#define ID_ITEM_IMPORTBOX               33208
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32844
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
